version: "3.8"

services:
    mongo:
        image: mongo:latest
        container_name: mongo_db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: db
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - db_network
volumes:
    mongo_data:
networks:
    db_network:
        driver: bridge
